<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <PEPExternalRoot Condition="'$(PEPExternalRoot)'==''">$(SolutionDir)External\External.Libraries\</PEPExternalRoot>
    <PEPExternalAssimpInclude Condition="'$(PEPExternalAssimpInclude)'==''">$(PEPExternalRoot)assimp\Include</PEPExternalAssimpInclude>
    <PEPExternalImGuiInclude Condition="'$(PEPExternalImGuiInclude)'==''">$(PEPExternalRoot)imgui\Include</PEPExternalImGuiInclude>
    <PEPExternalDxcInclude Condition="'$(PEPExternalDxcInclude)'==''">$(PEPExternalRoot)dxc\Include</PEPExternalDxcInclude>
    <PEPExternalPixInclude Condition="'$(PEPExternalPixInclude)'==''">$(PEPExternalRoot)pix\Include</PEPExternalPixInclude>
    <PEPExternalDirectXTKInclude Condition="'$(PEPExternalDirectXTKInclude)'==''">$(PEPExternalRoot)directxtk\Include</PEPExternalDirectXTKInclude>
    <PEPExternalDirectX-HeadersInclude Condition="'$(PEPExternalDirectX-HeadersInclude)'==''">$(PEPExternalRoot)directx-headers\Include</PEPExternalDirectX-HeadersInclude>
    <PEPExternalDirectXTexInclude Condition="'$(PEPExternalDirectXTexInclude)'==''">$(PEPExternalRoot)directxtex\Include</PEPExternalDirectXTexInclude>
    <PEPExternalDebugDrawerInclude Condition="'$(PEPExternalDebugDrawerInclude)'==''">$(PEPExternalRoot)debugdrawer\Include</PEPExternalDebugDrawerInclude>
    <PEPExternalFfxApiInclude Condition="'$(PEPExternalFfxApiInclude)'==''">$(PEPExternalRoot)ffx-api\Include</PEPExternalFfxApiInclude>
    <PEPExternalNvidiaSDKInclude Condition="'$(PEPExternalNvidiaSDKInclude)'==''">$(PEPExternalRoot)nvidia-sdk\Include</PEPExternalNvidiaSDKInclude>
    <PEPExternalDirectStorageInclude Condition="'$(PEPExternalDirectStorageInclude)'==''">$(PEPExternalRoot)directstorage\Include</PEPExternalDirectStorageInclude>
    <PEPExternalDirectXMeshInclude Condition="'$(PEPExternalDirectXMeshInclude)'==''">$(PEPExternalRoot)directxmesh\Include</PEPExternalDirectXMeshInclude>
    <PEPExternalWwiseInclude Condition="'$(PEPExternalWwiseInclude)'==''">$(PEPExternalRoot)wwise\Include</PEPExternalWwiseInclude>
    <PEPExternalWwiseSDKInclude Condition="'$(PEPExternalWwiseSDKInclude)'==''">$(PEPExternalRoot)wwise\Include\wwise</PEPExternalWwiseSDKInclude>
  </PropertyGroup>
</Project>
