<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildThisFileDirectory)PEPEngine.External.Assimp.props" Condition="Exists('$(MSBuildThisFileDirectory)PEPEngine.External.Assimp.props')" />
  <Import Project="$(MSBuildThisFileDirectory)PEPEngine.External.DirectXTK.props" Condition="Exists('$(MSBuildThisFileDirectory)PEPEngine.External.DirectXTK.props')" />
  <Import Project="$(MSBuildThisFileDirectory)PEPEngine.External.DirectX-Headers.props" Condition="Exists('$(MSBuildThisFileDirectory)PEPEngine.External.DirectX-Headers.props')" />
  <Import Project="$(MSBuildThisFileDirectory)PEPEngine.External.DirectXTex.props" Condition="Exists('$(MSBuildThisFileDirectory)PEPEngine.External.DirectXTex.props')" />
  <Import Project="$(MSBuildThisFileDirectory)PEPEngine.External.DebugDrawer.props" Condition="Exists('$(MSBuildThisFileDirectory)PEPEngine.External.DebugDrawer.props')" />
  <Import Project="$(MSBuildThisFileDirectory)PEPEngine.External.Ffx-api.props" Condition="Exists('$(MSBuildThisFileDirectory)PEPEngine.External.Ffx-api.props')" />
  <Import Project="$(MSBuildThisFileDirectory)PEPEngine.External.NvidiaSDK.props" Condition="Exists('$(MSBuildThisFileDirectory)PEPEngine.External.NvidiaSDK.props')" />
  <Import Project="$(MSBuildThisFileDirectory)PEPEngine.External.DirectStorage.props" Condition="Exists('$(MSBuildThisFileDirectory)PEPEngine.External.DirectStorage.props')" />
  <Import Project="$(MSBuildThisFileDirectory)PEPEngine.External.DirectXMesh.props" Condition="Exists('$(MSBuildThisFileDirectory)PEPEngine.External.DirectXMesh.props')" />
  <Import Project="$(MSBuildThisFileDirectory)PEPEngine.External.Wwise.props" Condition="Exists('$(MSBuildThisFileDirectory)PEPEngine.External.Wwise.props')" />
  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>$(SolutionDir)Engine\Engine.Core\Include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
  </ItemDefinitionGroup>
</Project>
